main/profiles/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, IntegerField
from wtforms.validators import ValidationError, DataRequired
from main.models import Profile, Order
import re

#Form class is a subclass of FlaskForm
class CreateProfile(FlaskForm):
    #class variables as fields
    username = StringField('Enter a name', validators=[DataRequired()])
    email = StringField('Enter an email', validators=[DataRequired()])
    submit = SubmitField('Create Profile')

    #'validate_<class variable>' notation checks that field's input upon form submission
    def validate_email(self, email):
        #regex for emails
        #source: https://www.geeksforgeeks.org/write-regular-expressions/
        mail = re.compile(r'^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$')

        #not in email format
        if not re.compile(mail).search(email.data):
            raise ValidationError('Enter enter an email in a valid format')
        
        if Profile.query.filter_by(email=email.data).first() != None:
            raise ValidationError('That email has already been taken')

class OrderProfileForm(FlaskForm):
    #form fields
    add_order = SelectField('Add / Modify items')
    add_quantity = StringField('Number of ordered item')
    remove_order = SelectField('Remove item from profile')
    submit = SubmitField('Save Changes')

    #variables can be passed into the form upon its initialization as an object
    def __init__(self, profile, *args, **kwargs):

        #__init__ for Editorder now has all the methods of FlaskForm
        super(OrderProfileForm, self).__init__(*args, **kwargs)
        self.profile = profile
        self.addedorder = ''

    def validate_add_order(self, add_order):
        #saves add_order for later validation
        self.addedorder = add_order.data
    
    def validate_add_quantity(self, add_quantity): 
        #add_order and add_quantity fields are filled
        if self.addedorder != 'Leave Blank' and add_quantity.data != '':
            try:
                if int(add_quantity.data) <= 0:
                    raise ValidationError('Quantity cannot be 0 or less')
            except:
                raise ValidationError('Quantity must be an integer')

            #queried Order object when first two fields are filled with acceptable data
            order = Order.query.filter_by(name=self.addedorder).first()
            #An entry for order with the same quantity already exists
            
            if self.profile.owns_order(order) and self.profile.order_quantity(order).quantity == int(add_quantity.data):
                raise ValidationError('Item already added')
      
        
        #additional exceptions
        #filled order and unfilled quantity
        if self.addedorder != 'Leave Blank' and add_quantity.data == '':
            raise ValidationError('Quantity of order cannot be blank')
        #filled quantity and unfilled order
        if self.addedorder == 'Leave Blank' and add_quantity.data != '':
            raise ValidationError('Order cannot be blank')
    
    #blank form is submitted
    def validate_remove_order(self, remove_order):
        if self.addedorder == 'Leave Blank' and remove_order.data == 'Leave Blank':
            raise ValidationError('No changes have been made')

class EmptyForm(FlaskForm):
    submit = SubmitField()

main/profiles/__init__.py
from flask import Blueprint

bp = Blueprint('profiles', __name__)

from main.profiles import routes, forms

main/profiles/routes.py
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required
from main import db
from main.profiles import bp
from main.profiles.forms import CreateProfile, OrderProfileForm, EmptyForm
from main.models import Profile, Order

#creates customer profile
@bp.route('/create-profile', methods=['GET', 'POST'])
@login_required
def create_profile():

    #intializes CreateProfile form
    form = CreateProfile()

    #form has valid input
    if form.validate_on_submit():
        #retrieves data from form fields (class variables)
        username = form.username.data
        email = form.email.data

        #creates profile with form data
        profile = Profile(username=username, email=email)
        db.session.add(profile)
        db.session.commit()

        flash('Profile added')
        return redirect(url_for('profiles.create_profile'))
    
    return render_template('profiles/createprofile.html', title='Create profile', form=form)

@bp.route('/deleteprofile/<id>', methods=['POST'])
@login_required
def delete_profile(id):
    form = EmptyForm()

    if form.validate_on_submit():
        profile = Profile.query.filter_by(id=id).first()
        if profile is None:
            flash(f'There is no profile with id {id}')
            return redirect(url_for('auth.index'))
        
        db.session.delete(profile)
        db.session.commit()
        flash('Deletion successful')
        return redirect(url_for('profiles.search_profile'))
    else:
        return redirect(url_for('auth.homepage'))

@bp.route('/searchprofile/', methods=['GET', 'POST'])
@login_required
def search_profile():
    form = EmptyForm()
    all_profiles = [f'{p.email}, {p.username}' for p in Profile.query.order_by('username')] #value label pairs to pass into form

    if form.validate_on_submit():
        choice = request.form['profile-choice']
        email = choice.split(', ')[0]
        if email != '':
            return redirect(url_for('profiles.manageprofile', email=email))
        else: 
            flash('Field cannot be blank')
            return redirect(url_for('profiles.search_profile'))

    return render_template('profiles/searchprofile.html', title='Search for Profile', profiles=all_profiles, form=form)

@bp.route('/manageprofile/<email>/', methods=['GET', 'POST'])
@login_required
def manageprofile(email):

    #finds first occurance of queried profile or returns None
    profile = Profile.query.filter_by(email=email).first()
    if profile is None:
        flash('Profile not found')
        return redirect(url_for('auth.homepage'))

    form = OrderProfileForm(profile)
    delete_form = EmptyForm()

    all_orders = [f.name for f in Order.query.order_by('name').all()] + ['Leave Blank']
    form.add_order.choices = all_orders

    obj_orders = profile.owned_orders().all()
    owned_orders = [f.name for f in obj_orders] + ['Leave Blank']
    form.remove_order.choices = owned_orders

    if form.validate_on_submit():
        order_name = form.add_order.data
        quantity = form.add_quantity.data
        remove_name = form.remove_order.data
        
        #filled in options each
        if order_name != 'Leave Blank':
            addedorder = Order.query.filter_by(name=order_name).first()

            if profile.owns_order(addedorder):
                profile.modify_order(addedorder, quantity)
                flash('Quantity successfully changed')
                db.session.commit()

            else:
                profile.add_order(addedorder, quantity)
                flash('Order has been successfully added to profile')
                db.session.commit()
    
        if remove_name != 'Leave Blank':
            removed_order = Order.query.filter_by(name=remove_name).first()
            profile.remove_order(removed_order)
            flash('Order has successfully been removed from profile')
            db.session.commit()

        return redirect(url_for('profiles.manageprofile', email=email))
    
    elif request.method == 'GET':
        form.add_order.data = 'Leave Blank'
        form.remove_order.data = 'Leave Blank'

    return render_template('profiles/manageprofile.html', title=f'{profile.username}\'s Profile', profile=profile, 
    orders= obj_orders, form=form, round=round, delete_form=delete_form
    )

main/templates/profiles/_profile.html
<td> {{ profile.id }} </td>
<td> {{ profile.username }} </td>
<td> {{ profile.email }} </td>

main/templates/profiles/createprofile.html
{% extends 'base.html' %}

{% block content %}
<!--submits the form to the current url (action='')-->
<form action='' method= 'post' novalidate>
    {{ form.hidden_tag() }}

    <!--acesses username variable of the form object, calling its label and field -->
    <p>
        {{ form.username.label }}
        {{ form.username(size=32) }}
        <!--flashes errors-->
        {% for error in form.username.errors %}
        {{ error }}
        {% endfor %}
    </p>

    <p>
        {{ form.email.label }}
        {{ form.email(size=45) }}
        {% for error in form.email.errors %}
        {{ error }}
        {% endfor %}
    </p>

    <!--submit field is called at the form's end-->
    {{ form.submit() }}
</form>
{% endblock %}

main/templates/profiles/manageprofile.html
{% extends 'base.html' %}
{% block content %}
<p>
    Profile ID = {{ profile.id }}
    Email = {{ profile.email }}
    <form action="{{ url_for('profiles.delete_profile', id=profile.id) }}" method="post">
        {{ delete_form.hidden_tag() }}
        {{ delete_form.submit(value='Delete Profile')}}
    </form>
</p>

<form action="" method="post" novalidate>
    {{ form.hidden_tag() }}
    <p>
        {{ form.add_order.label }}<br>
        {{ form.add_order() }}
        {% for error in form.add_order.errors %}
        {{ error }}
        {% endfor %}
        <br>
        {{ form.add_quantity.label }}
        {{ form.add_quantity() }}
        {% for error in form.add_quantity.errors %}
        {{ error }}
        {% endfor %}
    </p>

    <p>
        {{ form.remove_order.label }}<br>
        {{ form.remove_order() }}
        {% for error in form.remove_order.errors %}
        {{ error }}
        {% endfor %}
    </p>
    <p>{{ form.submit() }}</p>
</form>

<p>
    <table>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
        </tr>

        {% for order in orders %}

            <tr valign="top">
                {% include 'orders/_order.html' %}
                <td> {{ profile.order_quantity(order).quantity }}</td>
                <td> {{ round(order.price * profile.order_quantity(order).quantity, 2) }}</td>
            </tr>
            
        {% endfor %}
    </table>
</p>

{% endblock %}

main/templates/profiles/searchprofile.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post" novalidate>
    {{ form.hidden_tag() }}

    <p>
    <label for="profile-choice">Select a Profile:</label>
    <input list="profile-selection" id="profile-choice" name="profile-choice" />

    <datalist id="profile-selection">
        {% for profile in profiles %}
        <option value='{{ profile }}'>
        {% endfor %}
    </datalist>

    </p>

    <p>{{ form.submit(value='Search For Profile') }}</p>
</form>
{% endblock %}