main/orders/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired, ValidationError
from wtforms.fields import StringField, SubmitField
from main.models import Order
import re

#regular expression for money
#source: https://stackoverflow.com/questions/2150205/can-somebody-explain-a-money-regex-that-just-checks-if-the-value-matches-some-pa
money = re.compile('|'.join([
    r'^\$?(\d*\.\d{1,2})$',  # e.g., $.50, .50, $1.50, $.5, .5
    r'^\$?(\d+)$',           # e.g., $500, $5, 500, 5
    r'^\$(\d+\.?)$',         # e.g., $5.
    ]))

class MakeOrderForm(FlaskForm):
    #class variables as fields (label, validators)
    name = StringField('Enter order name', validators=[DataRequired()])
    price = StringField('Enter order price', validators=[DataRequired()])
    submit = SubmitField('Add order')

    #'validate_<class variable>' notation checks that field's input upon form submission
    def validate_name(self, name):
        #searches for entry with the same name regardless of capitalization
        order  = Order.query.with_entities(Order.name).\
        filter(Order.name.ilike(f"%{name.data}%")).first()

        if order != None:
            raise ValidationError('That order has already been added')
    
    def validate_price(self, price):
        #input not in money format
        if not re.compile(money).search(price.data):
            raise ValidationError('Enter cost in CAD')

class EditOrderForm(FlaskForm):
    newname = StringField('Order Name', validators=[DataRequired()])
    cost = StringField('Cost (CAD)', validators=[DataRequired()])
    submit = SubmitField('Save Changes')

    def __init__(self, order, *args, **kwargs):

        #__init__ for EditOrderForm now has all the methods of FlaskForm
        super(EditOrderForm, self).__init__(*args, **kwargs)
        self.original_name = order.name
        self.original_price = order.price
        self.changed_name = ''

    def validate_newname(self, newname):
        order = Order.query.filter_by(name=newname.data).first()

        #tries to change name to an order already in the database that does not have
        #its original name since name can be the same if price changes
        if order != None and newname.data != self.original_name:
            raise ValidationError('Enter a different item name')
        self.changed_name = newname.data

    def validate_cost(self, cost):
        
        #submits unchanged form
        if self.original_name == self.changed_name and str(self.original_price) == cost.data:
            raise ValidationError('At least one parameter must be changed')

        if not re.compile(money).search(cost.data):
            raise ValidationError('Enter cost in CAD')

class EmptyForm(FlaskForm):
    submit = SubmitField()

main/orders/__init__.py
from flask import Blueprint

bp = Blueprint('orders', __name__)

from main.orders import routes, forms

main/orders/routes.py
from main import db
from main.orders import bp
from flask import render_template, redirect, url_for, request, flash, request
from main.orders.forms import EditOrderForm, EmptyForm, MakeOrderForm
from flask_login import login_required
from main.models import Order

#route for deleting orders, only POST protocol since the form is empty
#(no fields to display for user input)
@bp.route('/deleteorder/<name>', methods=['POST'])
@login_required
def delete_order(name):

    #initializes form with only a SubmitField
    form = EmptyForm()

    if form.validate_on_submit():
        #order object to be deleted
        order = Order.query.filter_by(name=name).first()

        #delete order from database
        if order is None:
            flash(f'Item {name} does not exist')
            return redirect(url_for('orders.search_order'))

        db.session.delete(order)
        db.session.commit()
        flash('Deletion successful')
        return redirect(url_for('orders.search_order'))
    else:
        return redirect(url_for('orders.search_order'))

@bp.route('/makeorder', methods=['GET', 'POST'])
@login_required
def add_order():
    form = MakeOrderForm()

    if form.validate_on_submit():
        name = form.name.data
        price = form.price.data

        order = Order(name=name, price=price)
        db.session.add(order)
        db.session.commit()

        flash('Order successfully created!')
        return redirect(url_for('orders.add_order'))
    
    return render_template('orders/makeorder.html', title='Order creation', form=form )

@bp.route('/searchorder/', methods=['GET', 'POST'])
@login_required
def search_order():
    form = EmptyForm()
    #name of all orders passed into form as a list sorted by 'name' attribute of Order objects
    all_orders = [f.name for f in Order.query.order_by('name')] 

    if form.validate_on_submit():
        #client-side request object has a value for the 'order-choice' parameter of a submitted HTML form 
        name = request.form['order-choice']
        if name != '':
            #redirects with saved variable
            return redirect(url_for('orders.edit_order', ordername=name))
        else:
            flash('Field cannot be blank')
            return redirect(url_for('orders.search_order'))

    return render_template('orders/searchorder.html', title='Search for Order', orders=all_orders, form=form)

#route accepts ordername variable 
@bp.route('/editorder/<ordername>/', methods=['GET', 'POST'])
@login_required
#URL variable referenced in function parameter of the same name 
def edit_order(ordername):
    #order does not exist
    order = Order.query.filter_by(name=ordername).first()
    if order is None:
        flash('Item not found')
        return redirect(url_for('auth.homepage')) 
    
    #form initialization
    form = EditOrderForm(order)
    delete_form = EmptyForm()
    profiles_list = order.owner_profiles()

    if form.validate_on_submit():
        #updates Order attributes
        order.name = form.newname.data
        order.price = form.cost.data
        db.session.commit()
        flash('Entry has been updated')
        #refreshes the page
        return redirect(url_for('orders.edit_order', ordername=form.newname.data))

    #user recieves information from server
    elif request.method == 'GET':
        #fill in fields with default values
        form.newname.data = order.name
        form.cost.data = order.price
        
    return render_template('orders/editorder.html', title='Edit Order', form=form, delete_form=delete_form,
    name=ordername, profiles_list = profiles_list)

main/templates/orders/_order.html
<td> {{ order.id }} </td>
<td> {{ order.name }} </td>
<td> {{ order.price }} </td>

main/templates/orders/editorder.html
{% extends 'base.html' %}
{% block content %}
<p>
    <!--sends POST data to a different url than the one in the address bar.
    Action= is set to delete_order's URL with the deleted order's name as an argument-->
    <form action="{{ url_for('orders.delete_order', name=name) }}" method="post">
        {{ delete_form.hidden_tag() }}
        <!--value= adds a label-->
        {{ delete_form.submit(value='Delete Order')}}
    </form>
</p>


<form action="" method="post" novalidate>
    {{ form.hidden_tag() }}
    <p>
        {{ form.newname.label }}<br>
        {{ form.newname(size=32) }}
        {% for error in form.newname.errors %}
        {{ error }}
        {% endfor %}
    </p>

    <p>
        {{ form.cost.label }}<br>
        {{ form.cost(size=32) }}
        {% for error in form.cost.errors %}
        {{ error }}
        {% endfor %}
    </p>

    <p>{{ form.submit() }}</p>
</form>

<p>
    <table>
        <tr>
            <th>ID</th>
            <th>Username</th>
            <th>Email</th>
        </tr>

        {% for profile in profiles_list %}

            <tr valign="top">
                {% include 'profiles/_profile.html' %}
            </tr>
            
        {% endfor %}
    </table>
</p>
{% endblock %}

main/templates/orders/makeorder.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post" novalidate>
    {{ form.hidden_tag() }}
    <p>
        {{ form.name.label }}<br>
        {{ form.name(size=32) }}
        {% for error in form.name.errors %}
        {{ error }}
        {% endfor %}
    </p>

    <p>
        {{ form.price.label }}<br>
        {{ form.price(size=32) }}
        {% for error in form.price.errors %}
        {{ error }}
        {% endfor %}
    </p>

    <p>{{ form.submit() }}</p>
</form>
{% endblock %}

main/templates/orders/searchorder.html
{% extends 'base.html' %}
{% block content %}
<!--sends form data to URL in address bar-->
<form action="" method="post" novalidate>
    {{ form.hidden_tag() }}

    <p>
    <!--text label for form-->
    <label for="order-choice">Select a Order:</label>
    <!--creates the form order-choice using the list passed into the html template-->
    <input list="order-selection" id="order-choice" name="order-choice" />
    
    <!--datalist element created using above list-->
    <datalist id="order-selection">
        {% for order in orders %}
        <option value='{{ order }}'>
        {% endfor %}
    </datalist>

    </p>

    <p>{{ form.submit(value='Search For Order') }}</p>
</form>
{% endblock %}